Campo=$1
Fecha=`date +'%Y%m%d%H%M'`
echo "Inicio: "> /tmp/BTEQ_CONSUMOS_NO_RECONOCIDOS.txt
date >> /tmp/BTEQ_CONSUMOS_NO_RECONOCIDOS.txt

bteq <<EOF

.LOGON $Campo
.set maxerror 1
.EXPORT RESET
.MESSAGEOUT file=/data/Proyecto/Scripts/Logs/BTEQ_CONSUMOS_NO_RECONOCIDOS$Fecha.log;

SET QUERY_BAND = 'QueryRewrite=NO;' FOR SESSION;

-- ============================================================
-- PASO A: UPDATE de DECISIONFINAL desde la vista (CORREGIDO)
-- Solo llena DECISIONFINAL si A está vacío/NULL. Las decisiones
-- ya tomadas en A se respetan y conservan, sin importar el
-- valor que tenga B.
-- ============================================================
UPDATE A
FROM DWH_DINERS.BASE_CONSUMOS_NO_RECONOCIDOS_FINAL A,
     (SELECT IDREGISTRO, NUMERO_AUTORIZACION,
             NUMERO_OPERACION, NUMERO_CASO, CREACIONREGISTRO, DECISIONFINAL
      FROM DWH_VIEW.V_AUTOSERVICIO_CONSUMOS_NO_RECONOCIDOS_AUT
      WHERE DECISIONFINAL IS NOT NULL
        AND DECISIONFINAL <> ''
      -- Deduplicar por IDREGISTRO: nos quedamos con el registro más reciente
      QUALIFY ROW_NUMBER() OVER (PARTITION BY IDREGISTRO ORDER BY CREACIONREGISTRO DESC) = 1
     ) B
SET DECISIONFINAL = B.DECISIONFINAL
WHERE (A.DECISIONFINAL IS NULL OR A.DECISIONFINAL = '')
  AND A.IDREGISTRO = B.IDREGISTRO;


-- ============================================================
-- PASO A2: UPDATE de fechas desde la vista (CORREGIDO)
-- Cada fecha se actualiza de forma independiente, solo si A
-- está vacía y B tiene valor. Las fechas ya existentes en A
-- se respetan y conservan.
-- ============================================================

-- FECHA_DECISION_PREVIA
UPDATE A
FROM DWH_DINERS.BASE_CONSUMOS_NO_RECONOCIDOS_FINAL A,
     (SELECT IDREGISTRO, FECHA_DECISION_PREVIA, CREACIONREGISTRO
      FROM DWH_VIEW.V_AUTOSERVICIO_CONSUMOS_NO_RECONOCIDOS_AUT
      WHERE FECHA_DECISION_PREVIA IS NOT NULL
      QUALIFY ROW_NUMBER() OVER (PARTITION BY IDREGISTRO ORDER BY CREACIONREGISTRO DESC) = 1
     ) B
SET FECHA_DECISION_PREVIA = B.FECHA_DECISION_PREVIA
WHERE A.IDREGISTRO = B.IDREGISTRO
  AND A.FECHA_DECISION_PREVIA IS NULL;


-- FECHA_CONTRACARGO
UPDATE A
FROM DWH_DINERS.BASE_CONSUMOS_NO_RECONOCIDOS_FINAL A,
     (SELECT IDREGISTRO, FECHA_CONTRACARGO, CREACIONREGISTRO
      FROM DWH_VIEW.V_AUTOSERVICIO_CONSUMOS_NO_RECONOCIDOS_AUT
      WHERE FECHA_CONTRACARGO IS NOT NULL
      QUALIFY ROW_NUMBER() OVER (PARTITION BY IDREGISTRO ORDER BY CREACIONREGISTRO DESC) = 1
     ) B
SET FECHA_CONTRACARGO = B.FECHA_CONTRACARGO
WHERE A.IDREGISTRO = B.IDREGISTRO
  AND A.FECHA_CONTRACARGO IS NULL;


-- FECHA_DECISION_DEFINITIVA
UPDATE A
FROM DWH_DINERS.BASE_CONSUMOS_NO_RECONOCIDOS_FINAL A,
     (SELECT IDREGISTRO, FECHA_DECISION_DEFINITIVA, CREACIONREGISTRO
      FROM DWH_VIEW.V_AUTOSERVICIO_CONSUMOS_NO_RECONOCIDOS_AUT
      WHERE FECHA_DECISION_DEFINITIVA IS NOT NULL
      QUALIFY ROW_NUMBER() OVER (PARTITION BY IDREGISTRO ORDER BY CREACIONREGISTRO DESC) = 1
     ) B
SET FECHA_DECISION_DEFINITIVA = B.FECHA_DECISION_DEFINITIVA
WHERE A.IDREGISTRO = B.IDREGISTRO
  AND A.FECHA_DECISION_DEFINITIVA IS NULL;

DELETE FROM DWH_DINERS.BASE_CONSUMOS_NO_RECONOCIDOS_FINAL
WHERE ((DECISIONFINAL IS NULL OR DECISIONFINAL = '')
       AND VALXFAC_NUMBOLETA IS NULL) 
   OR MONTO_CARACTERISTICA_EVENTO IS NULL;


-- ============================================================
-- PASO B: AUTORIZACIONES_VS_CONSUMOS_NO_RECONOCIDOS
--         *** MODIFICADO: agregamos las 3 fechas desde BASE ***
-- ============================================================
DELETE FROM DWH_DINERS.AUTORIZACIONES_VS_CONSUMOS_NO_RECONOCIDOS ALL;

INSERT INTO DWH_DINERS.AUTORIZACIONES_VS_CONSUMOS_NO_RECONOCIDOS
SELECT DISTINCT
  BASE.IDREGISTRO,
  BASE.NUMERO_AUTORIZACION,
  BASE.NUMERO_CASO,
  BASE.NUMERO_OPERACION,
  BASE.ESTADO_CASO,
  BASE.CREACIONREGISTRO,
  BASE.MODIFICACIONREGISTRO,
  BASE.USUARIOCREACION,
  BASE.USUARIOMODIFICACION,
  BASE.DECISIONFINAL,
  AUT.ID_AUTORIZACION,
  AUT.CD_AUTORIZACION,
  AUT.NUM_OPERACION,
  AUT.FECHA_AUTORIZACION,
  -- *** Columnas nuevas al final ***
  BASE.FECHA_DECISION_PREVIA,
  BASE.FECHA_CONTRACARGO,
  BASE.FECHA_DECISION_DEFINITIVA
FROM DWH_VIEW.V_AUTOSERVICIO_CONSUMOS_NO_RECONOCIDOS_AUT BASE
LEFT JOIN DWH_DINERS.BASE_CONSUMOS_NO_RECONOCIDOS_FINAL B 
  ON BASE.IDREGISTRO = B.IDREGISTRO
LEFT JOIN DWH_VIEW.V_AUTORIZACION AUT 
  ON TRIM(BASE.NUMERO_OPERACION) = AUT.NUM_OPERACION
  AND CASE 
        WHEN REGEXP_SIMILAR(TRIM(OREPLACE(BASE.Numero_Autorizacion, CHR(26))), '^[0-9]+$') = 1
        THEN CAST(TRIM(OREPLACE(BASE.Numero_Autorizacion, CHR(26))) AS INTEGER)
        ELSE 0
      END = AUT.Cd_Autorizacion
  AND AUT.FECHA_AUTORIZACION > ADD_MONTHS(CURRENT_DATE, -3)
WHERE B.NUMERO_AUTORIZACION IS NULL
  AND BASE.NUMERO_AUTORIZACION IS NOT NULL 
  AND BASE.NUMERO_OPERACION IS NOT NULL
  AND ID_AUTORIZACION IS NOT NULL;


-- ============================================================
-- PASO C: Materialización del CAO (sin cambios)
-- ============================================================
DELETE FROM DWH_DINERS.ESTADO_CUENTA_DETALLE ALL;
INSERT INTO DWH_DINERS.ESTADO_CUENTA_DETALLE
  SELECT * FROM DWH_VIEW.V_ESTADO_CUENTA_DETALLE
  WHERE Fecha_Movimiento >= ADD_MONTHS(CURRENT_DATE, -4);

DELETE FROM DWH_DINERS.MOVIMIENTOS_X_FACTURAR ALL;
INSERT INTO DWH_DINERS.MOVIMIENTOS_X_FACTURAR
  SELECT * FROM DWH_VIEW.V_MOVIMIENTOS_X_FACTURAR
  WHERE Fecha_Movimiento >= ADD_MONTHS(CURRENT_DATE, -4);

DELETE FROM DWH_DINERS.PERSONA_SEGMENTO_COMERCIAL ALL;
INSERT INTO DWH_DINERS.PERSONA_SEGMENTO_COMERCIAL
  SELECT * FROM DWH_VIEW.V_PERSONA_SEGMENTO_COMERCIAL PSNS
  WHERE PSNS.Fecha_Inicio_Relacion <= CURRENT_DATE - 1
    AND PSNS.Fecha_Fin_Relacion > CURRENT_DATE - 1;

DELETE FROM DWH_DINERS.CUENTA_PRODUCTO_TARJETA_ESTADO ALL;
INSERT INTO DWH_DINERS.CUENTA_PRODUCTO_TARJETA_ESTADO
  SELECT ID_TARJETA, FECHA_INICIO_RELACION, ID_MOTIVO_CUENTA_PRODUCTO_TARJETA, 
         ID_ESTADO_CUENTA_PRODUCTO_TARJETA
  FROM DWH_VIEW.V_CUENTA_PRODUCTO_TARJETA_ESTADO A
  WHERE FECHA_FIN_RELACION = '3000-12-31'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ID_TARJETA 
                             ORDER BY FECHA_INICIO_RELACION DESC) = 1;

DELETE FROM DWH_DINERS.CUENTA ALL;
INSERT INTO DWH_DINERS.CUENTA SELECT * FROM DWH_VIEW.V_CUENTA;

DELETE FROM DWH_DINERS.CUENTA_PERSONA ALL;
INSERT INTO DWH_DINERS.CUENTA_PERSONA SELECT * FROM DWH_VIEW.V_CUENTA_PERSONA;

DELETE FROM DWH_DINERS.PERSONA ALL;
INSERT INTO DWH_DINERS.PERSONA SELECT * FROM DWH_VIEW.V_PERSONA;

DELETE FROM DWH_DINERS.CUENTA_PRODUCTO_TARJETA_UNICO ALL;
INSERT INTO DWH_DINERS.CUENTA_PRODUCTO_TARJETA_UNICO
  SELECT * FROM DWH_VIEW.V_CUENTA_PRODUCTO_TARJETA_UNICO
  WHERE FECHA_FIN_RELACION = '3000-12-31';


-- ============================================================
-- PASO D: CONSUMOS_NO_RECONOCIDOS_PROCESO
--         *** MODIFICADO: agregamos las 3 fechas desde AUT ***
-- ============================================================
DELETE FROM DWH_DINERS.CONSUMOS_NO_RECONOCIDOS_PROCESO ALL;

INSERT INTO DWH_DINERS.CONSUMOS_NO_RECONOCIDOS_PROCESO
SELECT
  AUT.IDREGISTRO,
  AUT.NUMERO_AUTORIZACION,
  AUT.NUMERO_CASO,
  AUT.NUMERO_OPERACION,
  AUT.ESTADO_CASO,
  AUT.CREACIONREGISTRO,
  AUT.MODIFICACIONREGISTRO,
  AUT.USUARIOCREACION,
  AUT.USUARIOMODIFICACION,
  AUT.DECISIONFINAL,
  CAO.*,
  AINT.CANTIDAD_CARACTERISTICA_EVENTO  AS INTENTOS_AUTORIZACION,
  TOKEN.TEXTO_CARACTERISTICA_EVENTO    AS TOKEN,
  AUEOO.TEXTO_CARACTERISTICA_EVENTO    AS ENTIDAD_ORIGEN,
  AUTPAIS.ID_PAIS,
  ADDITIONAL_POS.ADDITIONAL_POS,
  DESC_OPERACION,
  AUT_P.ID_CLIENTE,
  CVV2_PRESENCIA,
  MCC,
  IND.ELECTRONIC_COMMERCE_INDICATOR,
  PR.Texto_Caracteristica_Evento       AS PAGO_RAPIDO,
  TP.ID_TIPO_CREDITO,
  COD_ANTIGUO,
  -- *** Columnas nuevas al final ***
  AUT.FECHA_DECISION_PREVIA,
  AUT.FECHA_CONTRACARGO,
  AUT.FECHA_DECISION_DEFINITIVA
FROM (SELECT * FROM DWH_DINERS.AUTORIZACIONES_VS_CONSUMOS_NO_RECONOCIDOS) AUT
INNER JOIN DWH_DINERS.BASES_CAO_ESPECIFICAS CAO
  ON AUT.ID_AUTORIZACION = CAO.ID_AUTORIZACION
  AND CAO.FECHA_AUTORIZACION >= ADD_MONTHS(CURRENT_DATE, -3)
LEFT JOIN DWH_VIEW.V_AUTORIZACION_INTENTOS_AUTORIZACION AINT 
  ON AINT.ID_AUTORIZACION = AUT.ID_AUTORIZACION
LEFT JOIN DWH_VIEW.V_AUTORIZACION_TOKEN_ID TOKEN 
  ON TOKEN.ID_AUTORIZACION = AUT.ID_AUTORIZACION
LEFT JOIN DWH_VIEW.V_AUTORIZACION_ENTIDAD_ORIGEN_OPERACION AUEOO 
  ON AUEOO.ID_AUTORIZACION = AUT.ID_AUTORIZACION
LEFT JOIN DWH_VIEW.V_AUTORIZACION_PAIS_TRANSACCION AUTPAIS 
  ON AUTPAIS.ID_AUTORIZACION = AUT.ID_AUTORIZACION 
  AND AUTPAIS.FECHA_FIN_RELACION = '3000-12-31'
LEFT JOIN (
    SELECT ID_AUTORIZACION, RIGHT(TEXTO_CARACTERISTICA_EVENTO, 2) AS ADDITIONAL_POS
    FROM DWH_VIEW.V_AUTORIZACION_ADDITIONAL_POS_INF
) ADDITIONAL_POS ON ADDITIONAL_POS.ID_AUTORIZACION = AUT.ID_AUTORIZACION
LEFT JOIN (
    SELECT ID_AUTORIZACION, DESC_OPERACION
    FROM DWH_VIEW.V_AUTORIZACION_OPERACION A
    LEFT JOIN DWH_VIEW.V_OPERACION B ON A.ID_OPERACION = B.ID_OPERACION
    WHERE FECHA_FIN_RELACION = '3000-12-31'
) TIPO_AUT ON TIPO_AUT.ID_AUTORIZACION = AUT.ID_AUTORIZACION
LEFT JOIN DWH_VIEW.V_AUTORIZACION_CARACTERISTICA AUT_C 
  ON AUT.Id_Autorizacion = AUT_C.Id_Autorizacion 
  AND AUT_C.Id_Caracteristica = 19
LEFT JOIN DWH_VIEW.V_AUTORIZACION_CLIENTE AUT_P 
  ON AUT.Id_Autorizacion = AUT_P.Id_Autorizacion
LEFT JOIN DWH_VIEW.V_AUTORIZACION_CVV2_PRESENCIA CVV2 
  ON AUT.Id_Autorizacion = CVV2.Id_Autorizacion
LEFT JOIN DWH_VIEW.V_AUTORIZACION_MCC MCC 
  ON AUT.Id_Autorizacion = MCC.Id_Autorizacion
LEFT JOIN DWH_VIEW.V_AUTORIZACION_ELECTRONIC_COMMERCE_INDICATOR IND 
  ON AUT.Id_Autorizacion = IND.Id_Autorizacion
LEFT JOIN DWH_VIEW.V_AUTORIZACION_PAGO_RAPIDO PR 
  ON PR.Id_Autorizacion = AUT.Id_Autorizacion
LEFT JOIN DWH_VIEW.V_AUTORIZACION_TIPO_CREDITO TP 
  ON AUT.Id_Autorizacion = TP.Id_Autorizacion
LEFT JOIN (
    SELECT ID_AUTORIZACION, TEXTO_CARACTERISTICA_EVENTO AS COD_ANTIGUO
    FROM DWH_VIEW.V_AUTORIZACION_CARACTERISTICA
    WHERE ID_CARACTERISTICA = 13
) AUT_ANTIG ON AUT_ANTIG.ID_AUTORIZACION = AUT.ID_AUTORIZACION;


-- ============================================================
-- PASO E: VT_AUT_BASE (volatile)
--         *** MODIFICADO: agregamos las 3 fechas desde AUT ***
-- ============================================================
CREATE VOLATILE TABLE VT_AUT_BASE AS (
    SELECT
        AUT.IDREGISTRO,
        AUT.NUMERO_AUTORIZACION,
        AUT.NUMERO_CASO,
        AUT.NUMERO_OPERACION,
        AUT.Fecha_Autorizacion,
        AUT.Monto_Moneda_Local,
        AUT.Num_Operacion,
        AUT.Cd_Autorizacion,
        AUT.CREACIONREGISTRO,
        AUT.MODIFICACIONREGISTRO,
        AUT.USUARIOCREACION,
        AUT.USUARIOMODIFICACION,
        AUT.ID_TARJETA,
        AUT.LOC_EXTERNA,
        AUT.CVV2_PRESENCIA,
        AUT.MCC,
        COALESCE(AUT.ELECTRONIC_COMMERCE_INDICATOR, AUT.ADDITIONAL_POS) AS ELECTRONIC_COMMERCE_INDICATOR,
        AUT.PAGO_RAPIDO,
        AUT.ESTADO_CASO,
        AUT.INTENTOS_AUTORIZACION,
        AUT.TOKEN,
        AUT.ENTIDAD_ORIGEN,
        AUT.Hora_Inicio_Aut,
        AUT.Hora_Fin_Aut,
        AUT.DECISIONFINAL,
        AUT.DESC_OPERACION,
        AUT.COD_ANTIGUO,
        AUT.ID_TIPO_CREDITO,

        -- *** Columnas nuevas que se propagan ***
        AUT.FECHA_DECISION_PREVIA,
        AUT.FECHA_CONTRACARGO,
        AUT.FECHA_DECISION_DEFINITIVA,

        -- Persona / Cuenta
        CP.ID_PERSONA,
        CP.ID_CUENTA,
        CP.NUM_DOC_IDENTIFICACION                       AS Cedula,
        CPTU.NUM_DOC_IDENTIFICACION                     AS Cedula_TARJETA,
        CPTU.ID_PRODUCTO,
        P.DESC_NOMBRE,
        PAD.DESC_NOMBRE                                 AS DESC_NOMBRE_TARJETA,
        CUENTA.CD_CUENTA,
        TST.TARJETA_SISTEMA_REAL                        AS TARJETA,
        TSC.TARJETA_SISTEMA_REAL                        AS CUENTA_SISTEMA,
        EST.DESC_ESTABLECIMIENTO                        AS DESC_ESTABLECIMIENTO_AUEST,
        EST.CODIGO_ESTABLECIMIENTO,
        EST.DESC_ESTABLECIMIENTO,
        EST.DESC_ESPECIALIDAD,
        ESTAUT.DESC_ESTADO_AUTORIZACION,
        MOTAUT.CD_MOTIVO_ESTADO_AUTORIZACION,
        MOTAUT.DESC_MOTIVO_ESTADO_AUTORIZACION,
        TV.DESC_TIPO_VIA,
        PAIS.DESC_PAIS,
        SR.DESC_SUBRED,
        RED.DESC_RED,
        TPL.DESC_TIPO_LECTURA_TARJETA,
        CTC.DESC_TIPO_CREDITO,
        PRODU.CD_PRODUCTO,
        PRODU.NOMBRE_PRODUCTO,
        MAR.DESC_MARCA,
        SEG.DESC_SEGMENTO                               AS SEGMENTO_COMERCIAL,
        CPTE.CD_ESTADO_CUENTA_PRODUCTO_TARJETA,
        CPTE.DESC_ESTADO_CUENTA_PRODUCTO_TARJETA,
        CPTE.CD_MOTIVO_CUENTA_PRODUCTO_TARJETA,
        CPTE.DESC_MOTIVO_CUENTA_PRODUCTO_TARJETA,
        FECHA_BOL.FECHA_INICIO_RELACION                 AS FECHA_INICIO_BOLETIN,
        FECHA_CAN.FECHA_INICIO_RELACION                 AS FECHA_INICIO_CANCELACION

    FROM DWH_DINERS.CONSUMOS_NO_RECONOCIDOS_PROCESO AUT

    INNER JOIN (
        SELECT DESC_ESTABLECIMIENTO, ID_PERSONA, CODIGO_ESTABLECIMIENTO, DESC_ESPECIALIDAD
        FROM DWH_VIEW.V_PERSONA_ESPECIALIDAD_CADENA_ESTABLECIMIENTO
        WHERE ID_PERSONA IN (
            SELECT DISTINCT ID_ESTABLECIMIENTO
            FROM DWH_DINERS.CONSUMOS_NO_RECONOCIDOS_PROCESO
        )
    ) EST ON EST.ID_PERSONA = AUT.ID_ESTABLECIMIENTO

    INNER JOIN DWH_DINERS.CUENTA_PRODUCTO_TARJETA_UNICO CPTU
        ON CPTU.ID_PERSONA = AUT.ID_CLIENTE
        AND CPTU.ID_TARJETA = AUT.ID_TARJETA
        AND CPTU.FECHA_FIN_RELACION = '3000-12-31'
    INNER JOIN DWH_DINERS.CUENTA CUENTA 
        ON CUENTA.ID_CUENTA = CPTU.ID_CUENTA
    INNER JOIN DWH_DINERS.CUENTA_PERSONA CP
        ON CP.ID_CUENTA = CPTU.ID_CUENTA
        AND CP.FECHA_FIN_RELACION = '3000-12-31'
    INNER JOIN DWH_VIEW.V_TARJETA_SISTEMA TST 
        ON TST.Id_Tarjeta = AUT.ID_TARJETA
    INNER JOIN DWH_DINERS.CUENTA C 
        ON C.ID_CUENTA = CP.ID_CUENTA
    INNER JOIN DWH_VIEW.V_TARJETA_SISTEMA TSC 
        ON TSC.Id_Tarjeta = C.CD_CUENTA
    LEFT JOIN DWH_DINERS.PERSONA P 
        ON P.ID_PERSONA = CP.ID_PERSONA
    LEFT JOIN DWH_DINERS.PERSONA PAD 
        ON PAD.ID_PERSONA = CPTU.ID_PERSONA

    LEFT JOIN DWH_VIEW.V_ESTADO_AUTORIZACION ESTAUT
        ON ESTAUT.ID_ESTADO_AUTORIZACION = AUT.ID_ESTADO_AUTORIZACION
    LEFT JOIN DWH_VIEW.V_MOTIVO_ESTADO_AUTORIZACION MOTAUT
        ON MOTAUT.ID_MOTIVO_ESTADO_AUTORIZACION = AUT.ID_MOTIVO_ESTADO_CUENTA
    LEFT JOIN DWH_VIEW.V_TIPO_VIA TV ON TV.ID_TIPO_VIA = AUT.ID_TIPO_VIA
    LEFT JOIN DWH_VIEW.V_PAIS PAIS ON PAIS.ID_PAIS = AUT.ID_PAIS
    LEFT JOIN DWH_VIEW.V_SUBRED SR ON SR.ID_SUBRED = AUT.ID_SUBRED
    LEFT JOIN DWH_VIEW.V_RED RED ON RED.ID_RED = AUT.ID_RED
    LEFT JOIN DWH_VIEW.V_TIPO_LECTURA_TARJETA TPL
        ON TPL.ID_TIPO_LECTURA_TARJETA = AUT.ID_TIPO_LECTURA_TARJETA
    LEFT JOIN DWH_VIEW.V_TIPO_CREDITO CTC ON CTC.ID_TIPO_CREDITO = AUT.ID_TIPO_CREDITO

    LEFT JOIN DWH_VIEW.V_PRODUCTO PRODU ON PRODU.ID_PRODUCTO = CPTU.ID_PRODUCTO
    LEFT JOIN DWH_VIEW.V_MARCA MAR ON MAR.ID_MARCA = PRODU.ID_MARCA_PRODUCTO

    LEFT JOIN (
        SELECT A.ID_TARJETA,
               ECPT.CD_ESTADO_CUENTA_PRODUCTO_TARJETA,
               ECPT.DESC_ESTADO_CUENTA_PRODUCTO_TARJETA,
               MCPT.CD_MOTIVO_CUENTA_PRODUCTO_TARJETA,
               MCPT.DESC_MOTIVO_CUENTA_PRODUCTO_TARJETA
        FROM DWH_DINERS.CUENTA_PRODUCTO_TARJETA_ESTADO A
        LEFT JOIN DWH_VIEW.V_ESTADO_CUENTA_PRODUCTO_TARJETA ECPT
            ON ECPT.ID_ESTADO_CUENTA_PRODUCTO_TARJETA = A.ID_ESTADO_CUENTA_PRODUCTO_TARJETA
        LEFT JOIN DWH_VIEW.V_MOTIVO_CUENTA_PRODUCTO_TARJETA MCPT
            ON MCPT.ID_MOTIVO_CUENTA_PRODUCTO_TARJETA = A.ID_MOTIVO_CUENTA_PRODUCTO_TARJETA
        QUALIFY ROW_NUMBER() OVER (PARTITION BY A.ID_TARJETA 
                                   ORDER BY A.FECHA_INICIO_RELACION DESC) = 1
    ) CPTE ON CPTE.ID_TARJETA = AUT.ID_TARJETA

    LEFT JOIN DWH_DINERS.PERSONA_SEGMENTO_COMERCIAL PSNS
        ON PSNS.Id_Persona = CP.ID_PERSONA
    LEFT JOIN DWH_VIEW.V_SEGMENTO SEG 
        ON SEG.Id_Segmento = PSNS.Id_Segmento

    LEFT JOIN (
        SELECT ID_TARJETA, FECHA_INICIO_RELACION
        FROM DWH_DINERS.CUENTA_PRODUCTO_TARJETA_ESTADO
        WHERE ID_MOTIVO_CUENTA_PRODUCTO_TARJETA IN (1, 2, 3)
        QUALIFY ROW_NUMBER() OVER (PARTITION BY ID_TARJETA 
                                   ORDER BY FECHA_INICIO_RELACION DESC) = 1
    ) FECHA_BOL ON FECHA_BOL.ID_TARJETA = AUT.ID_TARJETA

    LEFT JOIN (
        SELECT ID_TARJETA, FECHA_INICIO_RELACION
        FROM DWH_DINERS.CUENTA_PRODUCTO_TARJETA_ESTADO
        WHERE ID_MOTIVO_CUENTA_PRODUCTO_TARJETA NOT IN (1, 2, 3)
        QUALIFY ROW_NUMBER() OVER (PARTITION BY ID_TARJETA 
                                   ORDER BY FECHA_INICIO_RELACION DESC) = 1
    ) FECHA_CAN ON FECHA_CAN.ID_TARJETA = AUT.ID_TARJETA

) WITH DATA
ON COMMIT PRESERVE ROWS;


-- ============================================================
-- PASOS XF, XF2, EC1, EC2, DESCARGO, DESCARGO_EC
-- (sin cambios respecto a la versión actual)
-- ============================================================
CREATE VOLATILE TABLE VT_XF AS (
    SELECT B.IDREGISTRO, XF.Num_Boleta, XF.Num_Recap, XF.Valor_Movimiento, XF.Valor_IVA,
           XF.FECHA_CORTE, XF.Id_Persona_Cuenta, XF.ID_CUENTA AS XF_ID_CUENTA,
           XF.Fecha_Movimiento AS XF_Fecha_Movimiento, XF.NUM_MOVIMIENTO AS XF_NUM_MOVIMIENTO
    FROM VT_AUT_BASE B
    INNER JOIN DWH_DINERS.MOVIMIENTOS_X_FACTURAR XF
        ON XF.Id_Persona_Cuenta = B.ID_PERSONA
        AND XF.ID_CUENTA = B.ID_CUENTA
        AND XF.Valor_Movimiento = B.Monto_Moneda_Local
        AND B.Fecha_Autorizacion BETWEEN XF.Fecha_Movimiento - 2 AND XF.Fecha_Movimiento + 2
    QUALIFY ROW_NUMBER() OVER (PARTITION BY B.IDREGISTRO
        ORDER BY ABS(B.Fecha_Autorizacion - XF.Fecha_Movimiento) ASC) = 1
) WITH DATA ON COMMIT PRESERVE ROWS;

CREATE VOLATILE TABLE VT_XF2 AS (
    SELECT B.IDREGISTRO, XF2.Num_Boleta, XF2.Num_Recap, XF2.Valor_Movimiento, XF2.Valor_IVA,
           XF2.FECHA_CORTE, XF2.Id_Persona_Cuenta
    FROM VT_AUT_BASE B
    LEFT JOIN VT_XF ON VT_XF.IDREGISTRO = B.IDREGISTRO
    INNER JOIN DWH_DINERS.MOVIMIENTOS_X_FACTURAR XF2
        ON XF2.Id_Persona_Cuenta = B.ID_PERSONA
        AND XF2.ID_CUENTA = B.ID_CUENTA
        AND XF2.ID_TPO_MOVIMIENTO = 1
        AND (ABS(B.Monto_Moneda_Local - XF2.Valor_Movimiento)
             / ((B.Monto_Moneda_Local + XF2.Valor_Movimiento) / 2)) * 100 <= 5.00
        AND B.Fecha_Autorizacion BETWEEN XF2.Fecha_Movimiento - 2 AND XF2.Fecha_Movimiento + 2
    WHERE VT_XF.IDREGISTRO IS NULL
    QUALIFY ROW_NUMBER() OVER (PARTITION BY B.IDREGISTRO
        ORDER BY ABS(B.Monto_Moneda_Local - XF2.Valor_Movimiento) ASC,
                 ABS(B.Fecha_Autorizacion - XF2.Fecha_Movimiento) ASC) = 1
) WITH DATA ON COMMIT PRESERVE ROWS;

CREATE VOLATILE TABLE VT_EC1 AS (
    SELECT B.IDREGISTRO, EC1.Num_Boleta, EC1.Num_Recap, EC1.Monto_Movimiento, EC1.Monto_IVA,
           EC1.FECHA_CORTE, EC1.Id_Persona, EC1.Id_Doc_Estado_Cuenta,
           EC1.ID_CUENTA AS EC1_ID_CUENTA, EC1.Fecha_Movimiento AS EC1_Fecha_Movimiento
    FROM VT_AUT_BASE B
    LEFT JOIN VT_XF ON VT_XF.IDREGISTRO = B.IDREGISTRO
    LEFT JOIN VT_XF2 ON VT_XF2.IDREGISTRO = B.IDREGISTRO
    INNER JOIN DWH_DINERS.ESTADO_CUENTA_DETALLE EC1
        ON EC1.Id_Persona = B.ID_PERSONA
        AND EC1.ID_CUENTA = B.ID_CUENTA
        AND EC1.Monto_Movimiento = B.Monto_Moneda_Local
        AND B.Fecha_Autorizacion BETWEEN EC1.Fecha_Movimiento - 2 AND EC1.Fecha_Movimiento + 2
    WHERE VT_XF.IDREGISTRO IS NULL AND VT_XF2.IDREGISTRO IS NULL
    QUALIFY ROW_NUMBER() OVER (PARTITION BY B.IDREGISTRO
        ORDER BY ABS(B.Fecha_Autorizacion - EC1.Fecha_Movimiento) ASC) = 1
) WITH DATA ON COMMIT PRESERVE ROWS;

CREATE VOLATILE TABLE VT_EC2 AS (
    SELECT B.IDREGISTRO, EC2.Num_Boleta, EC2.Num_Recap, EC2.Monto_Movimiento, EC2.Monto_IVA,
           EC2.FECHA_CORTE, EC2.Id_Persona, EC2.Id_Doc_Estado_Cuenta,
           EC2.ID_CUENTA AS EC2_ID_CUENTA, EC2.Fecha_Movimiento AS EC2_Fecha_Movimiento
    FROM VT_AUT_BASE B
    LEFT JOIN VT_XF ON VT_XF.IDREGISTRO = B.IDREGISTRO
    LEFT JOIN VT_XF2 ON VT_XF2.IDREGISTRO = B.IDREGISTRO
    LEFT JOIN VT_EC1 ON VT_EC1.IDREGISTRO = B.IDREGISTRO
    INNER JOIN DWH_DINERS.ESTADO_CUENTA_DETALLE EC2
        ON EC2.Id_Persona = B.ID_PERSONA
        AND EC2.ID_CUENTA = B.ID_CUENTA
        AND EC2.Cod_Tipo_Movimiento_Cuenta_Factura = 1
        AND (ABS(B.Monto_Moneda_Local - EC2.MONTO_MOVIMIENTO)
             / ((B.Monto_Moneda_Local + EC2.MONTO_MOVIMIENTO) / 2)) * 100 <= 5.00
        AND B.Fecha_Autorizacion BETWEEN EC2.Fecha_Movimiento - 2 AND EC2.Fecha_Movimiento + 2
    WHERE VT_XF.IDREGISTRO IS NULL AND VT_XF2.IDREGISTRO IS NULL AND VT_EC1.IDREGISTRO IS NULL
    QUALIFY ROW_NUMBER() OVER (PARTITION BY B.IDREGISTRO
        ORDER BY ABS(B.Monto_Moneda_Local - EC2.MONTO_MOVIMIENTO) ASC,
                 ABS(B.Fecha_Autorizacion - EC2.Fecha_Movimiento) ASC) = 1
) WITH DATA ON COMMIT PRESERVE ROWS;

CREATE VOLATILE TABLE VT_DESCARGO AS (
    SELECT DISTINCT XF.IDREGISTRO, D.VALOR_MOVIMIENTO AS DESCARGO_VALOR
    FROM VT_XF XF
    INNER JOIN DWH_DINERS.MOVIMIENTOS_X_FACTURAR D
        ON D.ID_CUENTA = XF.XF_ID_CUENTA
        AND D.Fecha_Movimiento = XF.XF_Fecha_Movimiento
        AND D.NUM_MOVIMIENTO = XF.XF_NUM_MOVIMIENTO
        AND D.VALOR_MOVIMIENTO = 1.70
) WITH DATA ON COMMIT PRESERVE ROWS;

CREATE VOLATILE TABLE VT_DESCARGO_EC AS (
    SELECT DISTINCT EC1.IDREGISTRO, D.MONTO_MOVIMIENTO AS DESCARGO_EC_VALOR
    FROM VT_EC1 EC1
    INNER JOIN DWH_DINERS.ESTADO_CUENTA_DETALLE D
        ON D.ID_CUENTA = EC1.EC1_ID_CUENTA
        AND D.Fecha_Movimiento = EC1.EC1_Fecha_Movimiento
        AND D.Id_Doc_Estado_Cuenta = EC1.Id_Doc_Estado_Cuenta
        AND D.MONTO_MOVIMIENTO = 1.70
) WITH DATA ON COMMIT PRESERVE ROWS;


-- ============================================================
-- PASO F: INSERT a BASE_CONSUMOS_NO_RECONOCIDOS
--         *** MODIFICADO: agregamos las 3 fechas desde B (VT_AUT_BASE) ***
-- ============================================================
INSERT INTO DWH_DINERS.BASE_CONSUMOS_NO_RECONOCIDOS
SELECT DISTINCT
    B.IDREGISTRO,
    B.NUMERO_AUTORIZACION,
    B.NUMERO_CASO,
    B.NUMERO_OPERACION,
    B.Fecha_Autorizacion,
    B.Monto_Moneda_Local                            AS Monto_Caracteristica_Evento,
    B.Num_Operacion,
    B.Cd_Autorizacion,
    B.CREACIONREGISTRO,
    B.MODIFICACIONREGISTRO,
    B.USUARIOCREACION,
    B.USUARIOMODIFICACION,
    B.Cedula,
    B.Cedula_TARJETA,
    B.TARJETA,
    B.DESC_TIPO_CREDITO,
    B.CUENTA_SISTEMA                                AS CUENTA,
    B.ID_TARJETA,
    B.CD_CUENTA,
    B.CD_ESTADO_CUENTA_PRODUCTO_TARJETA,
    B.DESC_ESTADO_CUENTA_PRODUCTO_TARJETA,
    B.CD_MOTIVO_CUENTA_PRODUCTO_TARJETA,
    B.DESC_MOTIVO_CUENTA_PRODUCTO_TARJETA,
    B.DESC_NOMBRE,
    B.DESC_NOMBRE_TARJETA,
    B.DESC_ESTABLECIMIENTO_AUEST,
    B.LOC_EXTERNA                                   AS Loc_Externa,
    COALESCE(XF.Num_Boleta, XF2.Num_Boleta, EC1.Num_Boleta, EC2.Num_Boleta)                         AS ValXFac_NumBoleta,
    COALESCE(XF.Num_Recap, XF2.Num_Recap, EC1.Num_Recap, EC2.Num_Recap)                             AS ValXFac_Num_Recap,
    COALESCE(XF.Valor_Movimiento, XF2.Valor_Movimiento, EC1.Monto_Movimiento, EC2.Monto_Movimiento) AS Valor_Movimiento,
    COALESCE(XF.Valor_IVA, XF2.Valor_IVA, EC1.Monto_IVA, EC2.Monto_IVA)                             AS Valor_IVA,
    COALESCE(XF.FECHA_CORTE, XF2.FECHA_CORTE, EC1.FECHA_CORTE, EC2.FECHA_CORTE)                     AS FECHA_CORTE,
    COALESCE(XF.Id_Persona_Cuenta, XF2.Id_Persona_Cuenta, EC1.Id_Persona, EC2.Id_Persona)           AS Id_Persona_Cuenta,
    COALESCE(EC1.Id_Doc_Estado_Cuenta, EC2.Id_Doc_Estado_Cuenta)                                     AS EstadoCuentaDoc,
    NULL                                            AS IMPUESTO_SALIDA_DIVISAS,
    NULL                                            AS RETENCION_IVA_SERV_DIGITALES,
    B.DESC_SUBRED,
    B.DESC_TIPO_LECTURA_TARJETA,
    B.DESC_RED,
    B.CODIGO_ESTABLECIMIENTO,
    B.DESC_ESTABLECIMIENTO,
    B.CVV2_PRESENCIA,
    B.MCC,
    B.ELECTRONIC_COMMERCE_INDICATOR,
    B.PAGO_RAPIDO,
    CURRENT_DATE                                    AS FECHA_INGRESO,
    B.ESTADO_CASO                                   AS DESC_ESTADO,
    B.DESC_MARCA,
    B.DESC_ESPECIALIDAD,
    B.SEGMENTO_COMERCIAL,
    B.CD_PRODUCTO,
    B.NOMBRE_PRODUCTO,
    NULL                                            AS TARJETA_TOKENIZADA,
    CASE
        WHEN COALESCE(XF.Num_Boleta, XF2.Num_Boleta, EC1.Num_Boleta, EC2.Num_Boleta) IS NULL
        THEN 'NO FACTURADO' ELSE 'FACTURADO'
    END                                             AS FACTURADO_NOFACTURADO,
    B.DESC_ESTADO_AUTORIZACION,
    B.DESC_TIPO_VIA,
    B.INTENTOS_AUTORIZACION,
    B.TOKEN,
    B.ENTIDAD_ORIGEN,
    B.DESC_PAIS,
    B.Hora_Inicio_Aut                               AS HORA_INICIO_AUTORIZACION,
    B.Hora_Fin_Aut                                  AS HORA_FIN_AUTORIZACION,
    B.CD_MOTIVO_ESTADO_AUTORIZACION                 AS CODIGO_RESOLUCION,
    B.DESC_MOTIVO_ESTADO_AUTORIZACION               AS RESOLUCION,
    CASE
        WHEN B.CD_MOTIVO_CUENTA_PRODUCTO_TARJETA <> 0 AND B.FECHA_INICIO_BOLETIN IS NOT NULL
        THEN B.FECHA_INICIO_BOLETIN
        WHEN B.CD_MOTIVO_CUENTA_PRODUCTO_TARJETA <> 0 AND B.FECHA_INICIO_BOLETIN IS NULL
        THEN B.FECHA_INICIO_CANCELACION
    END                                             AS FECHA_BOLETIN,
    CASE
        WHEN B.DESC_ESTADO_CUENTA_PRODUCTO_TARJETA <> 'Activo'
        THEN B.FECHA_INICIO_CANCELACION
    END                                             AS FECHA_CANCELACION,
    COALESCE(DESCARGO.DESCARGO_VALOR, DESCARGO_EC.DESCARGO_EC_VALOR) AS AUTOSERVICIO_DESCARGO,
    B.DECISIONFINAL,
    B.DESC_OPERACION                                AS DESC_TIPO_AUTORIZACION,
    B.COD_ANTIGUO,
    -- *** Columnas nuevas al final ***
    B.FECHA_DECISION_PREVIA,
    B.FECHA_CONTRACARGO,
    B.FECHA_DECISION_DEFINITIVA
FROM VT_AUT_BASE B
LEFT JOIN VT_XF XF           ON XF.IDREGISTRO = B.IDREGISTRO
LEFT JOIN VT_XF2 XF2         ON XF2.IDREGISTRO = B.IDREGISTRO
LEFT JOIN VT_EC1 EC1         ON EC1.IDREGISTRO = B.IDREGISTRO
LEFT JOIN VT_EC2 EC2         ON EC2.IDREGISTRO = B.IDREGISTRO
LEFT JOIN VT_DESCARGO DESCARGO       ON DESCARGO.IDREGISTRO = B.IDREGISTRO
LEFT JOIN VT_DESCARGO_EC DESCARGO_EC ON DESCARGO_EC.IDREGISTRO = B.IDREGISTRO;

DROP TABLE VT_AUT_BASE;
DROP TABLE VT_XF;
DROP TABLE VT_XF2;
DROP TABLE VT_EC1;
DROP TABLE VT_EC2;
DROP TABLE VT_DESCARGO;
DROP TABLE VT_DESCARGO_EC;


-- ============================================================
-- PASO G: BASE_CONSUMOS_NO_RECONOCIDOS_TELF
--         *** MODIFICADO: AUT.* expandido + 3 fechas al final ***
-- ============================================================
DELETE FROM DWH_DINERS.BASE_CONSUMOS_NO_RECONOCIDOS_TELF ALL;

CREATE VOLATILE TABLE VT_CEL AS (
    SELECT AUT.CD_CUENTA AS CNCOPR, AUT.CEDULA AS SCDOPR,
        CASE CNAUCMAP.CNPOSI
            WHEN 1 THEN SOCDIRP.SCPRE1 || CAST(CAST(SOCDIRP.SCTEL1 AS BIGINT) AS VARCHAR(10))
            WHEN 2 THEN SOCDIRP.SCPRE2 || CAST(CAST(SOCDIRP.SCTEL2 AS BIGINT) AS VARCHAR(10))
            WHEN 3 THEN SOCDIRP.SCPRE3 || CAST(CAST(SOCDIRP.SCTEL3 AS BIGINT) AS VARCHAR(10))
            WHEN 4 THEN SOCDIRP.SCPRE4 || CAST(CAST(SOCDIRP.SCTEL4 AS BIGINT) AS VARCHAR(10))
        END AS CELULAR
    FROM (SELECT DISTINCT CD_CUENTA, CEDULA 
          FROM DWH_DINERS.BASE_CONSUMOS_NO_RECONOCIDOS) AUT
    INNER JOIN DWH_PRESTAGE.DVMCOMUN_CNAUCMAP CNAUCMAP
        ON AUT.CD_CUENTA = CNAUCMAP.CNCOPR
        AND CNAUCMAP.CNCDCA = 1268 AND CNAUCMAP.CNCDTC = 'C'
    INNER JOIN DWH_PRESTAGE.DCCLUNI_SOCDIRP SOCDIRP
        ON AUT.CEDULA = SOCDIRP.SCDOPR
        AND CNAUCMAP.CNSECU = SOCDIRP.SCENCU
    QUALIFY ROW_NUMBER() OVER (PARTITION BY AUT.CD_CUENTA, AUT.CEDULA
                               ORDER BY CNAUCMAP.CNSECU ASC) = 1
) WITH DATA ON COMMIT PRESERVE ROWS;

CREATE VOLATILE TABLE VT_EML AS (
    SELECT AUT.CD_CUENTA AS CNCOPR, AUT.CEDULA AS SCDOPR, SOCDIRP_1.SCMAIL AS EMAIL
    FROM (SELECT DISTINCT CD_CUENTA, CEDULA 
          FROM DWH_DINERS.BASE_CONSUMOS_NO_RECONOCIDOS) AUT
    INNER JOIN DWH_PRESTAGE.DVMCOMUN_CNAUCMAP CNAUCMAP_1
        ON AUT.CD_CUENTA = CNAUCMAP_1.CNCOPR
        AND CNAUCMAP_1.CNCDCA = 1268 AND CNAUCMAP_1.CNCDTC = 'M'
    INNER JOIN DWH_PRESTAGE.DCCLUNI_SOCDIRP SOCDIRP_1
        ON AUT.CEDULA = SOCDIRP_1.SCDOPR
        AND CNAUCMAP_1.CNSECU = SOCDIRP_1.SCENCU
    QUALIFY ROW_NUMBER() OVER (PARTITION BY AUT.CD_CUENTA, AUT.CEDULA
                               ORDER BY CNAUCMAP_1.CNSECU ASC) = 1
) WITH DATA ON COMMIT PRESERVE ROWS;

-- Se expande AUT.* a columnas explícitas para que CELULAR/EMAIL queden 
-- antes de las 3 columnas nuevas (que van al final de la tabla).
INSERT INTO DWH_DINERS.BASE_CONSUMOS_NO_RECONOCIDOS_TELF
SELECT
    AUT.IdRegistro,
    AUT.Numero_Autorizacion,
    AUT.Numero_Caso,
    AUT.Numero_Operacion,
    AUT.Fecha_Autorizacion,
    AUT.Monto_Caracteristica_Evento,
    AUT.Num_Operacion,
    AUT.Cd_Autorizacion,
    AUT.CreacionRegistro,
    AUT.ModificacionRegistro,
    AUT.UsuarioCreacion,
    AUT.UsuarioModificacion,
    AUT.Cedula,
    AUT.Cedula_TARJETA,
    AUT.TARJETA,
    AUT.Desc_Tipo_Credito,
    AUT.CUENTA,
    AUT.Id_Tarjeta,
    AUT.Cd_Cuenta,
    AUT.Cd_Estado_Cuenta_Producto_Tarjeta,
    AUT.Desc_Estado_Cuenta_Producto_Tarjeta,
    AUT.Cd_Motivo_Cuenta_Producto_Tarjeta,
    AUT.Desc_Motivo_Cuenta_Producto_Tarjeta,
    AUT.Desc_Nombre,
    AUT.DESC_NOMBRE_TARJETA,
    AUT.DESC_ESTABLECIMIENTO_AUEST,
    AUT.Loc_Externa,
    AUT.ValXFac_NumBoleta,
    AUT.ValXFac_Num_Recap,
    AUT.Valor_Movimiento,
    AUT.Valor_IVA,
    AUT.FECHA_CORTE,
    AUT.Id_Persona_Cuenta,
    AUT.EstadoCuentaDoc,
    AUT.IMPUESTO_SALIDA_DIVISAS,
    AUT.RETENCION_IVA_SERV_DIGITALES,
    AUT.Desc_SubRed,
    AUT.Desc_Tipo_Lectura_Tarjeta,
    AUT.Desc_Red,
    AUT.Codigo_Establecimiento,
    AUT.Desc_Establecimiento,
    AUT.CVV2_presencia,
    AUT.MCC,
    AUT.Electronic_Commerce_Indicator,
    AUT.PAGO_RAPIDO,
    AUT.FECHA_INGRESO,
    AUT.DESC_ESTADO,
    AUT.Desc_Marca,
    AUT.Desc_Especialidad,
    AUT.SEGMENTO_COMERCIAL,
    AUT.Cd_Producto,
    AUT.Nombre_Producto,
    AUT.TARJETA_TOKENIZADA,
    AUT.FACTURADO_NOFACTURADO,
    AUT.Desc_Estado_Autorizacion,
    AUT.Desc_Tipo_Via,
    AUT.INTENTOS_AUTORIZACION,
    AUT.TOKEN,
    AUT.ENTIDAD_ORIGEN,
    AUT.Desc_Pais,
    AUT.Hora_Inicio_Autorizacion,
    AUT.Hora_Fin_Autorizacion,
    AUT.CODIGO_RESOLUCION,
    AUT.RESOLUCION,
    AUT.FECHA_BOLETIN,
    AUT.FECHA_CANCELACION,
    AUT.AUTOSERVICIO_DESCARGO,
    AUT.DecisionFinal,
    AUT.DESC_TIPO_AUTORIZACION,
    AUT.COD_ANTIGUO,
    CEL.CELULAR,
    LOWER(EML.EMAIL)                AS EMAIL,
    -- *** Columnas nuevas al final ***
    AUT.FECHA_DECISION_PREVIA,
    AUT.FECHA_CONTRACARGO,
    AUT.FECHA_DECISION_DEFINITIVA
FROM DWH_DINERS.BASE_CONSUMOS_NO_RECONOCIDOS AUT
LEFT JOIN VT_CEL CEL ON AUT.CD_CUENTA = CEL.CNCOPR AND AUT.CEDULA = CEL.SCDOPR
LEFT JOIN VT_EML EML ON AUT.CD_CUENTA = EML.CNCOPR AND AUT.CEDULA = EML.SCDOPR;


-- ============================================================
-- PASO H: BASE_CONSUMOS_NO_RECONOCIDOS_FINAL (INSERT inicial)
--         *** MODIFICADO: A.* expandido + 3 fechas al final ***
-- ============================================================
INSERT INTO DWH_DINERS.BASE_CONSUMOS_NO_RECONOCIDOS_FINAL
SELECT
    A.IdRegistro,
    A.Numero_Autorizacion,
    A.Numero_Caso,
    A.Numero_Operacion,
    A.Fecha_Autorizacion,
    A.Monto_Caracteristica_Evento,
    A.Num_Operacion,
    A.Cd_Autorizacion,
    A.CreacionRegistro,
    A.ModificacionRegistro,
    A.UsuarioCreacion,
    A.UsuarioModificacion,
    A.Cedula,
    A.Cedula_TARJETA,
    A.TARJETA,
    A.Desc_Tipo_Credito,
    A.CUENTA,
    A.Id_Tarjeta,
    A.Cd_Cuenta,
    A.Cd_Estado_Cuenta_Producto_Tarjeta,
    A.Desc_Estado_Cuenta_Producto_Tarjeta,
    A.Cd_Motivo_Cuenta_Producto_Tarjeta,
    A.Desc_Motivo_Cuenta_Producto_Tarjeta,
    A.Desc_Nombre,
    A.DESC_NOMBRE_TARJETA,
    A.DESC_ESTABLECIMIENTO_AUEST,
    A.Loc_Externa,
    A.ValXFac_NumBoleta,
    A.ValXFac_Num_Recap,
    A.Valor_Movimiento,
    A.Valor_IVA,
    A.FECHA_CORTE,
    A.Id_Persona_Cuenta,
    A.EstadoCuentaDoc,
    A.IMPUESTO_SALIDA_DIVISAS,
    A.RETENCION_IVA_SERV_DIGITALES,
    A.Desc_SubRed,
    A.Desc_Tipo_Lectura_Tarjeta,
    A.Desc_Red,
    A.Codigo_Establecimiento,
    A.Desc_Establecimiento,
    A.CVV2_presencia,
    A.MCC,
    A.Electronic_Commerce_Indicator,
    A.PAGO_RAPIDO,
    A.FECHA_INGRESO,
    A.DESC_ESTADO,
    A.Desc_Marca,
    A.Desc_Especialidad,
    A.SEGMENTO_COMERCIAL,
    A.Cd_Producto,
    A.Nombre_Producto,
    A.TARJETA_TOKENIZADA,
    A.FACTURADO_NOFACTURADO,
    A.Desc_Estado_Autorizacion,
    A.Desc_Tipo_Via,
    A.INTENTOS_AUTORIZACION,
    A.TOKEN,
    A.ENTIDAD_ORIGEN,
    A.Desc_Pais,
    A.Hora_Inicio_Autorizacion,
    A.Hora_Fin_Autorizacion,
    A.CODIGO_RESOLUCION,
    A.RESOLUCION,
    A.FECHA_BOLETIN,
    A.FECHA_CANCELACION,
    A.AUTOSERVICIO_DESCARGO,
    A.DecisionFinal,
    A.DESC_TIPO_AUTORIZACION,
    A.COD_ANTIGUO,
    A.CELULAR,
    A.EMAIL,
    CASE
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'POS' AND A.DESC_TIPO_LECTURA_TARJETA = '05 Tarjeta inteligente' AND A.MONTO_CARACTERISTICA_EVENTO > 30 THEN 'PAGA SOCIO'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'POS' AND A.DESC_TIPO_LECTURA_TARJETA = '05 Tarjeta inteligente' AND A.MONTO_CARACTERISTICA_EVENTO <= 30 THEN 'P&G'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'POS' AND A.DESC_TIPO_LECTURA_TARJETA = '02 Banda magnética' AND A.MONTO_CARACTERISTICA_EVENTO > 25 THEN 'CONTRACARGO'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'POS' AND A.DESC_TIPO_LECTURA_TARJETA = '02 Banda magnética' AND A.MONTO_CARACTERISTICA_EVENTO <= 25 THEN 'P&G'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'POS' AND A.DESC_TIPO_LECTURA_TARJETA = '01 Manual' AND A.MONTO_CARACTERISTICA_EVENTO > 25 THEN 'CONTRACARGO'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'POS' AND A.DESC_TIPO_LECTURA_TARJETA = '01 Manual' AND A.MONTO_CARACTERISTICA_EVENTO <= 25 THEN 'P&G'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'POS' AND A.DESC_TIPO_LECTURA_TARJETA = '07 Contactless con chip' AND A.MONTO_CARACTERISTICA_EVENTO > 30 THEN 'PAGA SOCIO'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'POS' AND A.DESC_TIPO_LECTURA_TARJETA = '07 Contactless con chip' AND A.MONTO_CARACTERISTICA_EVENTO <= 30 THEN 'P&G'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'POS' AND A.DESC_TIPO_LECTURA_TARJETA = '90 Lectura Total del track' AND A.MONTO_CARACTERISTICA_EVENTO > 25 THEN 'CONTRACARGO'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'POS' AND A.DESC_TIPO_LECTURA_TARJETA = '90 Lectura Total del track' AND A.MONTO_CARACTERISTICA_EVENTO <= 25 THEN 'P&G'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'ATM' THEN 'PAGA SOCIO'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'INTERNET' AND A.ELECTRONIC_COMMERCE_INDICATOR = '05' AND A.MONTO_CARACTERISTICA_EVENTO > 30 THEN 'PAGA SOCIO'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'INTERNET' AND A.ELECTRONIC_COMMERCE_INDICATOR = '05' AND A.MONTO_CARACTERISTICA_EVENTO <= 30 THEN 'P&G'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'INTERNET' AND A.ELECTRONIC_COMMERCE_INDICATOR = '04' AND A.MONTO_CARACTERISTICA_EVENTO > 30 THEN 'PAGA SOCIO'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'INTERNET' AND A.ELECTRONIC_COMMERCE_INDICATOR = '04' AND A.MONTO_CARACTERISTICA_EVENTO <= 30 THEN 'P&G'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'INTERNET' AND A.ELECTRONIC_COMMERCE_INDICATOR = '06' THEN 'P&G'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'INTERNET' AND (A.ELECTRONIC_COMMERCE_INDICATOR NOT IN ('06','05','212','211','0103212','04','0103242') OR A.ELECTRONIC_COMMERCE_INDICATOR IS NULL) AND A.MONTO_CARACTERISTICA_EVENTO > 25 THEN 'CONTRACARGO'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'INTERNET' AND (A.ELECTRONIC_COMMERCE_INDICATOR NOT IN ('06','05','212','211','0103212','04','0103242') OR A.ELECTRONIC_COMMERCE_INDICATOR IS NULL) AND A.MONTO_CARACTERISTICA_EVENTO <= 25 THEN 'P&G'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'MANUAL' AND A.ELECTRONIC_COMMERCE_INDICATOR = '05' AND A.MONTO_CARACTERISTICA_EVENTO > 30 THEN 'PAGA SOCIO'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'MANUAL' AND A.ELECTRONIC_COMMERCE_INDICATOR = '05' AND A.MONTO_CARACTERISTICA_EVENTO <= 30 THEN 'P&G'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'MANUAL' AND A.ELECTRONIC_COMMERCE_INDICATOR = '04' AND A.MONTO_CARACTERISTICA_EVENTO > 30 THEN 'PAGA SOCIO'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'MANUAL' AND A.ELECTRONIC_COMMERCE_INDICATOR = '04' AND A.MONTO_CARACTERISTICA_EVENTO <= 30 THEN 'P&G'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'MANUAL' AND A.ELECTRONIC_COMMERCE_INDICATOR = '06' THEN 'P&G'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'MANUAL' AND (A.ELECTRONIC_COMMERCE_INDICATOR NOT IN ('06','05','212','211','0103212','04','0103242') OR A.ELECTRONIC_COMMERCE_INDICATOR IS NULL) AND A.MONTO_CARACTERISTICA_EVENTO > 25 THEN 'CONTRACARGO'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'MANUAL' AND (A.ELECTRONIC_COMMERCE_INDICATOR NOT IN ('06','05','212','211','0103212','04','0103242') OR A.ELECTRONIC_COMMERCE_INDICATOR IS NULL) AND A.MONTO_CARACTERISTICA_EVENTO <= 25 THEN 'P&G'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'INTERNET' AND A.ELECTRONIC_COMMERCE_INDICATOR = '212' AND A.MONTO_CARACTERISTICA_EVENTO > 30 THEN 'PAGA SOCIO'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'INTERNET' AND A.ELECTRONIC_COMMERCE_INDICATOR = '212' AND A.MONTO_CARACTERISTICA_EVENTO <= 30 THEN 'P&G'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'INTERNET' AND A.ELECTRONIC_COMMERCE_INDICATOR = '0103212' AND A.MONTO_CARACTERISTICA_EVENTO > 30 THEN 'PAGA SOCIO'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'INTERNET' AND A.ELECTRONIC_COMMERCE_INDICATOR = '0103212' AND A.MONTO_CARACTERISTICA_EVENTO <= 30 THEN 'P&G'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'INTERNET' AND A.ELECTRONIC_COMMERCE_INDICATOR = '0103242' AND A.MONTO_CARACTERISTICA_EVENTO > 30 THEN 'PAGA SOCIO'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'INTERNET' AND A.ELECTRONIC_COMMERCE_INDICATOR = '0103242' AND A.MONTO_CARACTERISTICA_EVENTO <= 30 THEN 'P&G'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'INTERNET' AND A.ELECTRONIC_COMMERCE_INDICATOR = '211' THEN 'P&G'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'INTERNET' AND (A.ELECTRONIC_COMMERCE_INDICATOR NOT IN ('212','211','0103212','06','05','04','0103242') OR A.ELECTRONIC_COMMERCE_INDICATOR IS NULL) AND A.MONTO_CARACTERISTICA_EVENTO > 25 THEN 'CONTRACARGO'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'INTERNET' AND (A.ELECTRONIC_COMMERCE_INDICATOR NOT IN ('212','211','0103212','06','05','04','0103242') OR A.ELECTRONIC_COMMERCE_INDICATOR IS NULL) AND A.MONTO_CARACTERISTICA_EVENTO <= 25 THEN 'P&G'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'MANUAL' AND A.ELECTRONIC_COMMERCE_INDICATOR = '212' AND A.MONTO_CARACTERISTICA_EVENTO > 30 THEN 'PAGA SOCIO'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'MANUAL' AND A.ELECTRONIC_COMMERCE_INDICATOR = '212' AND A.MONTO_CARACTERISTICA_EVENTO <= 30 THEN 'P&G'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'MANUAL' AND A.ELECTRONIC_COMMERCE_INDICATOR = '0103212' AND A.MONTO_CARACTERISTICA_EVENTO > 30 THEN 'PAGA SOCIO'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'MANUAL' AND A.ELECTRONIC_COMMERCE_INDICATOR = '0103212' AND A.MONTO_CARACTERISTICA_EVENTO <= 30 THEN 'P&G'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'MANUAL' AND A.ELECTRONIC_COMMERCE_INDICATOR = '0103242' AND A.MONTO_CARACTERISTICA_EVENTO > 30 THEN 'PAGA SOCIO'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'MANUAL' AND A.ELECTRONIC_COMMERCE_INDICATOR = '0103242' AND A.MONTO_CARACTERISTICA_EVENTO <= 30 THEN 'P&G'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'MANUAL' AND A.ELECTRONIC_COMMERCE_INDICATOR = '211' THEN 'P&G'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'MANUAL' AND (A.ELECTRONIC_COMMERCE_INDICATOR NOT IN ('212','211','0103212','06','05','04','0103242') OR A.ELECTRONIC_COMMERCE_INDICATOR IS NULL) AND A.MONTO_CARACTERISTICA_EVENTO > 25 THEN 'CONTRACARGO'
        WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'MANUAL' AND (A.ELECTRONIC_COMMERCE_INDICATOR NOT IN ('212','211','0103212','06','05','04','0103242') OR A.ELECTRONIC_COMMERCE_INDICATOR IS NULL) AND A.MONTO_CARACTERISTICA_EVENTO <= 25 THEN 'P&G'
        WHEN A.DESC_RED = 'PROPIAS' AND A.DESC_SUBRED = 'INTERNET' AND BCDC.COD_UNICO IS NOT NULL THEN 'DEBITO COMERCIO'
        WHEN A.DESC_RED = 'PROPIAS' AND A.DESC_SUBRED = 'INTERNET' AND (BCDC.COD_UNICO IS NULL OR BCDC.COD_UNICO = '') AND A.MONTO_CARACTERISTICA_EVENTO > 30 THEN 'PAGA SOCIO'
        WHEN A.DESC_RED = 'PROPIAS' AND A.DESC_SUBRED = 'INTERNET' AND (BCDC.COD_UNICO IS NULL OR BCDC.COD_UNICO = '') AND A.MONTO_CARACTERISTICA_EVENTO <= 30 THEN 'P&G'
        WHEN A.DESC_RED = 'PROPIAS' AND A.DESC_SUBRED = 'ATM' THEN 'PAGA SOCIO'
        WHEN A.DESC_RED = 'PROPIAS' AND A.DESC_SUBRED = 'POS' AND BCDC.COD_UNICO IS NOT NULL THEN 'DEBITO COMERCIO'
        WHEN A.DESC_RED = 'PROPIAS' AND A.PAGO_RAPIDO = 'R' THEN 'P&G'
        WHEN A.DESC_RED = 'PROPIAS' AND A.MONTO_CARACTERISTICA_EVENTO > 30 THEN 'PETICION COPIA DE VALE'
        WHEN A.DESC_RED = 'PROPIAS' AND A.MONTO_CARACTERISTICA_EVENTO <= 30 THEN 'P&G'
        WHEN A.DESC_RED = 'PROPIAS' AND A.DESC_SUBRED = 'POS' AND (BCDC.COD_UNICO IS NULL OR BCDC.COD_UNICO = '') THEN 'PAGA SOCIO'
    END                                             AS DECISION,
    'NO'                                            AS SOCIO_ALTO_VALOR,
    -- *** Columnas nuevas al final ***
    A.FECHA_DECISION_PREVIA,
    A.FECHA_CONTRACARGO,
    A.FECHA_DECISION_DEFINITIVA
FROM DWH_DINERS.BASE_CONSUMOS_NO_RECONOCIDOS_TELF A
LEFT JOIN DWH_TEMP.BASE_CODIGOS_DEBITO_COMERCIO BCDC 
    ON A.CODIGO_ESTABLECIMIENTO = TRIM(BCDC.COD_UNICO)
LEFT JOIN DWH_DINERS.BASE_CONSUMOS_NO_RECONOCIDOS_FINAL B 
    ON A.IDREGISTRO = B.IDREGISTRO
WHERE B.NUMERO_AUTORIZACION IS NULL;


-- ============================================================
-- PASO I: Deduplicación por IdRegistro (sin cambios)
-- ============================================================
DELETE FROM DWH_DINERS.BASE_CONSUMOS_NO_RECONOCIDOS_FINAL t
WHERE t.IdRegistro IN (
    SELECT IdRegistro FROM DWH_DINERS.BASE_CONSUMOS_NO_RECONOCIDOS_FINAL
    GROUP BY IdRegistro HAVING COUNT(*) > 1)
  AND t.FECHA_INGRESO < (
    SELECT MAX(FECHA_INGRESO) FROM DWH_DINERS.BASE_CONSUMOS_NO_RECONOCIDOS_FINAL s
    WHERE s.IdRegistro = t.IdRegistro);


-- ============================================================
-- PASO J: SOCIO_ALTO_VALOR (sin cambios)
-- ============================================================
UPDATE A
FROM DWH_DINERS.BASE_CONSUMOS_NO_RECONOCIDOS_FINAL A, 
     DWH_PRESTAGE.BASE_SOCIOS_ALTO_VALOR B
SET SOCIO_ALTO_VALOR = 'SI'
WHERE A.CEDULA_TARJETA = B.NUM_DOC_IDENTIFICACION 
  AND A.DECISIONFINAL IS NULL;

UPDATE A
FROM DWH_DINERS.BASE_CONSUMOS_NO_RECONOCIDOS_FINAL A, 
     DWH_PRESTAGE.BASE_SOCIOS_ALTO_VALOR B
SET SOCIO_ALTO_VALOR = 'SI'
WHERE A.CEDULA = B.NUM_DOC_IDENTIFICACION 
  AND A.DECISIONFINAL IS NULL;


-- ============================================================
-- PASO K: UPDATE DECISION para SOCIO_ALTO_VALOR='NO' (sin cambios)
-- ============================================================
UPDATE A
FROM DWH_DINERS.BASE_CONSUMOS_NO_RECONOCIDOS_FINAL A
LEFT JOIN DWH_TEMP.BASE_CODIGOS_DEBITO_COMERCIO BCDC
    ON A.CODIGO_ESTABLECIMIENTO = TRIM(BCDC.COD_UNICO)
SET DECISION = CASE
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'POS' AND A.DESC_TIPO_LECTURA_TARJETA = '05 Tarjeta inteligente' AND A.MONTO_CARACTERISTICA_EVENTO > 30 THEN 'PAGA SOCIO'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'POS' AND A.DESC_TIPO_LECTURA_TARJETA = '05 Tarjeta inteligente' AND A.MONTO_CARACTERISTICA_EVENTO <= 30 THEN 'P&G'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'POS' AND A.DESC_TIPO_LECTURA_TARJETA = '02 Banda magnética' AND A.MONTO_CARACTERISTICA_EVENTO > 25 THEN 'CONTRACARGO'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'POS' AND A.DESC_TIPO_LECTURA_TARJETA = '02 Banda magnética' AND A.MONTO_CARACTERISTICA_EVENTO <= 25 THEN 'P&G'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'POS' AND A.DESC_TIPO_LECTURA_TARJETA = '01 Manual' AND A.MONTO_CARACTERISTICA_EVENTO > 25 THEN 'CONTRACARGO'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'POS' AND A.DESC_TIPO_LECTURA_TARJETA = '01 Manual' AND A.MONTO_CARACTERISTICA_EVENTO <= 25 THEN 'P&G'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'POS' AND A.DESC_TIPO_LECTURA_TARJETA = '07 Contactless con chip' AND A.MONTO_CARACTERISTICA_EVENTO > 30 THEN 'PAGA SOCIO'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'POS' AND A.DESC_TIPO_LECTURA_TARJETA = '07 Contactless con chip' AND A.MONTO_CARACTERISTICA_EVENTO <= 30 THEN 'P&G'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'POS' AND A.DESC_TIPO_LECTURA_TARJETA = '90 Lectura Total del track' AND A.MONTO_CARACTERISTICA_EVENTO > 25 THEN 'CONTRACARGO'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'POS' AND A.DESC_TIPO_LECTURA_TARJETA = '90 Lectura Total del track' AND A.MONTO_CARACTERISTICA_EVENTO <= 25 THEN 'P&G'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'ATM' THEN 'PAGA SOCIO'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'INTERNET' AND A.ELECTRONIC_COMMERCE_INDICATOR = '05' AND A.MONTO_CARACTERISTICA_EVENTO > 30 THEN 'PAGA SOCIO'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'INTERNET' AND A.ELECTRONIC_COMMERCE_INDICATOR = '05' AND A.MONTO_CARACTERISTICA_EVENTO <= 30 THEN 'P&G'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'INTERNET' AND A.ELECTRONIC_COMMERCE_INDICATOR = '04' AND A.MONTO_CARACTERISTICA_EVENTO > 30 THEN 'PAGA SOCIO'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'INTERNET' AND A.ELECTRONIC_COMMERCE_INDICATOR = '04' AND A.MONTO_CARACTERISTICA_EVENTO <= 30 THEN 'P&G'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'INTERNET' AND A.ELECTRONIC_COMMERCE_INDICATOR = '06' THEN 'P&G'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'INTERNET' AND A.ELECTRONIC_COMMERCE_INDICATOR = '212' AND A.MONTO_CARACTERISTICA_EVENTO > 30 THEN 'PAGA SOCIO'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'INTERNET' AND A.ELECTRONIC_COMMERCE_INDICATOR = '212' AND A.MONTO_CARACTERISTICA_EVENTO <= 30 THEN 'P&G'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'INTERNET' AND A.ELECTRONIC_COMMERCE_INDICATOR = '0103212' AND A.MONTO_CARACTERISTICA_EVENTO > 30 THEN 'PAGA SOCIO'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'INTERNET' AND A.ELECTRONIC_COMMERCE_INDICATOR = '0103212' AND A.MONTO_CARACTERISTICA_EVENTO <= 30 THEN 'P&G'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'INTERNET' AND A.ELECTRONIC_COMMERCE_INDICATOR = '0103242' AND A.MONTO_CARACTERISTICA_EVENTO > 30 THEN 'PAGA SOCIO'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'INTERNET' AND A.ELECTRONIC_COMMERCE_INDICATOR = '0103242' AND A.MONTO_CARACTERISTICA_EVENTO <= 30 THEN 'P&G'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'INTERNET' AND A.ELECTRONIC_COMMERCE_INDICATOR = '211' THEN 'P&G'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'INTERNET' AND (A.ELECTRONIC_COMMERCE_INDICATOR NOT IN ('06','05','212','211','0103212','04','0103242') OR A.ELECTRONIC_COMMERCE_INDICATOR IS NULL) AND A.MONTO_CARACTERISTICA_EVENTO > 25 THEN 'CONTRACARGO'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'INTERNET' AND (A.ELECTRONIC_COMMERCE_INDICATOR NOT IN ('06','05','212','211','0103212','04','0103242') OR A.ELECTRONIC_COMMERCE_INDICATOR IS NULL) AND A.MONTO_CARACTERISTICA_EVENTO <= 25 THEN 'P&G'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'MANUAL' AND A.ELECTRONIC_COMMERCE_INDICATOR = '05' AND A.MONTO_CARACTERISTICA_EVENTO > 30 THEN 'PAGA SOCIO'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'MANUAL' AND A.ELECTRONIC_COMMERCE_INDICATOR = '05' AND A.MONTO_CARACTERISTICA_EVENTO <= 30 THEN 'P&G'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'MANUAL' AND A.ELECTRONIC_COMMERCE_INDICATOR = '04' AND A.MONTO_CARACTERISTICA_EVENTO > 30 THEN 'PAGA SOCIO'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'MANUAL' AND A.ELECTRONIC_COMMERCE_INDICATOR = '04' AND A.MONTO_CARACTERISTICA_EVENTO <= 30 THEN 'P&G'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'MANUAL' AND A.ELECTRONIC_COMMERCE_INDICATOR = '06' THEN 'P&G'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'MANUAL' AND A.ELECTRONIC_COMMERCE_INDICATOR = '212' AND A.MONTO_CARACTERISTICA_EVENTO > 30 THEN 'PAGA SOCIO'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'MANUAL' AND A.ELECTRONIC_COMMERCE_INDICATOR = '212' AND A.MONTO_CARACTERISTICA_EVENTO <= 30 THEN 'P&G'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'MANUAL' AND A.ELECTRONIC_COMMERCE_INDICATOR = '0103212' AND A.MONTO_CARACTERISTICA_EVENTO > 30 THEN 'PAGA SOCIO'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'MANUAL' AND A.ELECTRONIC_COMMERCE_INDICATOR = '0103212' AND A.MONTO_CARACTERISTICA_EVENTO <= 30 THEN 'P&G'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'MANUAL' AND A.ELECTRONIC_COMMERCE_INDICATOR = '0103242' AND A.MONTO_CARACTERISTICA_EVENTO > 30 THEN 'PAGA SOCIO'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'MANUAL' AND A.ELECTRONIC_COMMERCE_INDICATOR = '0103242' AND A.MONTO_CARACTERISTICA_EVENTO <= 30 THEN 'P&G'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'MANUAL' AND A.ELECTRONIC_COMMERCE_INDICATOR = '211' THEN 'P&G'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'MANUAL' AND (A.ELECTRONIC_COMMERCE_INDICATOR NOT IN ('06','05','212','211','0103212','04','0103242') OR A.ELECTRONIC_COMMERCE_INDICATOR IS NULL) AND A.MONTO_CARACTERISTICA_EVENTO > 25 THEN 'CONTRACARGO'
    WHEN A.DESC_RED = 'AJENA' AND A.DESC_SUBRED = 'MANUAL' AND (A.ELECTRONIC_COMMERCE_INDICATOR NOT IN ('06','05','212','211','0103212','04','0103242') OR A.ELECTRONIC_COMMERCE_INDICATOR IS NULL) AND A.MONTO_CARACTERISTICA_EVENTO <= 25 THEN 'P&G'
    WHEN A.DESC_RED = 'PROPIAS' AND A.DESC_SUBRED = 'INTERNET' AND BCDC.COD_UNICO IS NOT NULL THEN 'DEBITO COMERCIO'
    WHEN A.DESC_RED = 'PROPIAS' AND A.DESC_SUBRED = 'INTERNET' AND (BCDC.COD_UNICO IS NULL OR BCDC.COD_UNICO = '') AND A.MONTO_CARACTERISTICA_EVENTO > 30 THEN 'PAGA SOCIO'
    WHEN A.DESC_RED = 'PROPIAS' AND A.DESC_SUBRED = 'INTERNET' AND (BCDC.COD_UNICO IS NULL OR BCDC.COD_UNICO = '') AND A.MONTO_CARACTERISTICA_EVENTO <= 30 THEN 'P&G'
    WHEN A.DESC_RED = 'PROPIAS' AND A.DESC_SUBRED = 'ATM' THEN 'PAGA SOCIO'
    WHEN A.DESC_RED = 'PROPIAS' AND A.DESC_SUBRED = 'POS' AND BCDC.COD_UNICO IS NOT NULL THEN 'DEBITO COMERCIO'
    WHEN A.DESC_RED = 'PROPIAS' AND A.PAGO_RAPIDO = 'R' THEN 'P&G'
    WHEN A.DESC_RED = 'PROPIAS' AND A.MONTO_CARACTERISTICA_EVENTO > 30 THEN 'PETICION COPIA DE VALE'
    WHEN A.DESC_RED = 'PROPIAS' AND A.MONTO_CARACTERISTICA_EVENTO <= 30 THEN 'P&G'
    WHEN A.DESC_RED = 'PROPIAS' AND A.DESC_SUBRED = 'POS' AND (BCDC.COD_UNICO IS NULL OR BCDC.COD_UNICO = '') THEN 'PAGA SOCIO'
END
WHERE A.SOCIO_ALTO_VALOR = 'NO' AND A.DECISIONFINAL IS NULL;


-- ============================================================
-- PASO L: WO0000000249808 - Excepción Alto Valor (sin cambios)
-- ============================================================
UPDATE T
FROM DWH_DINERS.BASE_CONSUMOS_NO_RECONOCIDOS_FINAL T,
    (SELECT Cedula, SUM(Monto_Caracteristica_Evento) AS suma_monto
     FROM DWH_DINERS.BASE_CONSUMOS_NO_RECONOCIDOS_FINAL
     WHERE DECISION = 'PAGA SOCIO' AND SOCIO_ALTO_VALOR = 'SI' AND DecisionFinal IS NULL
     GROUP BY Cedula) X
SET DECISION = CASE
    WHEN X.suma_monto < 1000 THEN 'EXCEPCION ALTO VALOR'
    ELSE 'COMITE FRAUDES'
END
WHERE T.Cedula = X.Cedula AND T.DECISION = 'PAGA SOCIO' 
  AND T.SOCIO_ALTO_VALOR = 'SI' AND T.DecisionFinal IS NULL;
  

.IF ERRORCODE <> 0 THEN .EXIT ERRORCODE;

.LOGOFF
.quit;
EOF
echo "Fin: ">> /tmp/BTEQ_CONSUMOS_NO_RECONOCIDOS.txt
date >> /tmp/BTEQ_CONSUMOS_NO_RECONOCIDOS.txt



